language: node_js
node_js:
- stable
dist: trusty
sudo: false
addons:
  chrome: stable
cache:
  directories:
  - node_modules
script:
- npm test
after_success:
- cat ./coverage/lcov.info | node node_modules/.bin/coveralls
before_deploy:
- npm run build
deploy:
- on:
    branch: master
  provider: firebase
  skip_cleanup: true
- on:
    branch: beta
  provider: firebase
  project: beta
  skip_cleanup: true