language: node_js
node_js:
- stable
dist: trusty
sudo: false
addons:
  chrome: stable
cache:
  directories:
  - node_modules
script:
- npm test
after_success:
- cat ./coverage/lcov.info | node node_modules/.bin/coveralls
before_deploy:
- npm run build
- npm install -g firebase-tools firebase
deploy:
- true:
    branch: master
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN"
  skip_cleanup: true
- true:
    branch: beta
  provider: script
  script: firebase deploy --token "$FIREBASE_TOKEN" --project "beta"
  skip_cleanup: true
